stages:
  - lint
  - test

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

before_script:
  - pip install tox

lint:
  stage: lint
  image: python:3.6
  script: tox -e lint

test_python27:
  stage: test
  image: python:2.7
  script: tox -e 'py27-django{18,19,110}'

test_python34:
  stage: test
  image: python:3.4
  script: tox -e 'py34-django{18,19,110}'

test_python35:
  stage: test
  image: python:3.5
  script: tox -e 'py35-django{18,19,110}'

test_python36:
  stage: test
  image: python:3.6
  script: tox -e 'py36-django{18,19,110}'
